#pragma once

// NOTE : Item¿« ≈Î«’ ∞¸∏Æ ≈¨∑°Ω∫¥Ÿ.
//        Icon, Model (droped on ground), Game Data

#include "../eterLib/GrpSubImage.h"
#include "../eterGrnLib/Thing.h"
#include "GameLibDefines.h"
#ifdef ENABLE_INGAME_WIKI
#	include "WikiTable.h"
#endif

class CItemData
{
public:
	enum
	{
#ifdef ENABLE_PROTO_RENEWAL_CUSTOM
		ITEM_NAME_MAX_LEN = 40,	//@fixme429
#else
		ITEM_NAME_MAX_LEN = 24,
#endif
		ITEM_LIMIT_MAX_NUM = 2,
		ITEM_VALUES_MAX_NUM = 6,
		ITEM_SMALL_DESCR_MAX_LEN = 256,
#ifdef ENABLE_PROTO_RENEWAL
		ITEM_APPLY_MAX_NUM = 4,
#else
		ITEM_APPLY_MAX_NUM = 3,
#endif
#ifdef ENABLE_PROTO_RENEWAL
		ITEM_SOCKET_MAX_NUM = 6,
#else
		ITEM_SOCKET_MAX_NUM = 3,
#endif
#ifdef ENABLE_PICK_ROD_REFINE_RENEWAL
		ITEM_PICK_MAX_LEVEL = 9,
		ITEM_ROD_MAX_LEVEL = 20,
#endif
	};

#ifdef ENABLE_SOULBIND_SYSTEM
	enum ESealBind
	{
		SEAL_BIND_FLAG_DROP,
		SEAL_BIND_FLAG_UPGRADE,
		SEAL_BIND_FLAG_SELL,
		SEAL_BIND_FLAG_ENCHANT,
		SEAL_BIND_FLAG_TRADE,
		SEAL_BIND_FLAG_UNSEAL,
		SEAL_BIND_FLAG_MAX
	};

	enum ESealDate
	{
		SEAL_DATE_DEFAULT_TIMESTAMP = 0, // 2015/11/12 it's -1
	};

	enum ESealItem
	{
		SEAL_ITEM_BINDING_VNUM = 50263,
		SEAL_ITEM_UNBINDING_VNUM = 50264
	};
#endif

#ifdef ENABLE_GROWTH_PET_SYSTEM
	enum EPetData
	{
		//Hatching
		EGG_USE_SUCCESS = 0,
		EGG_USE_FAILED_BECAUSE_NAME = 1,
		EGG_USE_FAILED_TIMEOVER = 2,

		//ChangeName
		NAME_CHANGE_USE_SUCCESS = 0,
		NAME_CHANGE_USE_FAILED_BECAUSE_NAME = 1,

		GROWTH_PET_ITEM_USE_COOL_TIME = 1,
		PET_EGG_USE_TRUE = 0,
		PET_EGG_USE_FAILED_BECAUSE_TRADING = 1,
		PET_EGG_USE_FAILED_BECAUSE_SHOP_OPEN = 2,
		PET_EGG_USE_FAILED_BECAUSE_MALL_OPEN = 3,
		PET_EGG_USE_FAILED_BECAUSE_SAFEBOX_OPEN = 4,
		PET_HATCHING_MONEY = 1000000,
		PET_NAME_MAX_SIZE = 20,
		PET_NAME_MIN_SIZE = 4
	};

	enum EPetSubTypes
	{
		PET_EGG,
		PET_UPBRINGING,
		PET_BAG,
		PET_FEEDSTUFF,
		PET_SKILL,
		PET_SKILL_DEL_BOOK,
		PET_NAME_CHANGE,
		PET_EXPFOOD,
		PET_SKILL_ALL_DEL_BOOK,
		PET_EXPFOOD_PER,
		PET_ITEM_TYPE,
		PET_ATTR_CHANGE,
		PET_PAY,
		PET_PREMIUM_FEEDSTUFF	//PET_PREMIUM_FEEDSTUFF
	};

	enum EPetSkillData
	{
		PET_SKILL_AFFECT_NONE,
		PET_SKILL_AFFECT_JIJOONG_WARRIOR,
		PET_SKILL_AFFECT_JIJOONG_SURA,
		PET_SKILL_AFFECT_JIJOONG_ASSASSIN,
		PET_SKILL_AFFECT_JIJOONG_SHAMAN,
		PET_SKILL_AFFECT_JIJOONG_WOLFMAN,
		PET_SKILL_AFFECT_PACHEON,
		PET_SKILL_AFFECT_CHEONRYEONG,
		PET_SKILL_AFFECT_BANYA,
		PET_SKILL_AFFECT_CHOEHOENBIMU,
		PET_SKILL_AFFECT_HEAL,
		PET_SKILL_AFFECT_STEALHP,
		PET_SKILL_AFFECT_STEALMP,
		PET_SKILL_AFFECT_BLOCK,
		PET_SKILL_AFFECT_REFLECT_MELEE,
		PET_SKILL_AFFECT_GOLD_DROP,
		PET_SKILL_AFFECT_BOW_DISTANCE,
		PET_SKILL_AFFECT_INVINCIBILITY,
		PET_SKILL_AFFECT_REMOVAL,
		PET_SKILL_AFFECT_POTION,
		PET_SKILL_AFFECT_MOB_BONUS,
		PET_SKILL_AFFECT_EXP,
		PET_SKILL_HP_RECOVER,
		PET_SKILL_FEATHER,
		PET_SKILL_AFFECT_MAX,
	};
#endif

#ifdef ENABLE_PASSIVE_SYSTEM
	enum EPassiveAttrData
	{
		PASSIVE_JOB = 0,
	};
#endif

	enum EAcceMisc
	{
		ACCE_GRADE_MAX_NUM = 4,
	};

	enum EItemType
	{
		ITEM_TYPE_NONE,					//0
		ITEM_TYPE_WEAPON,				//1
		ITEM_TYPE_ARMOR,				//2
		ITEM_TYPE_USE,					//3
		ITEM_TYPE_AUTOUSE,				//4
		ITEM_TYPE_MATERIAL,				//5
		ITEM_TYPE_SPECIAL,				//6
		ITEM_TYPE_TOOL,					//7
		ITEM_TYPE_LOTTERY,				//8
		ITEM_TYPE_ELK,					//9
		ITEM_TYPE_METIN,				//10
		ITEM_TYPE_CONTAINER,			//11
		ITEM_TYPE_FISH,					//12
		ITEM_TYPE_ROD,					//13
		ITEM_TYPE_RESOURCE,				//14
		ITEM_TYPE_CAMPFIRE,				//15
		ITEM_TYPE_UNIQUE,				//16
		ITEM_TYPE_SKILLBOOK,			//17
		ITEM_TYPE_QUEST,				//18
		ITEM_TYPE_POLYMORPH,			//19
		ITEM_TYPE_TREASURE_BOX,			//20
		ITEM_TYPE_TREASURE_KEY,			//21
		ITEM_TYPE_SKILLFORGET,			//22
		ITEM_TYPE_GIFTBOX,				//23
		ITEM_TYPE_PICK,					//24
		ITEM_TYPE_HAIR,					//25
		ITEM_TYPE_TOTEM,				//26
		ITEM_TYPE_BLEND,				//27
		ITEM_TYPE_COSTUME,				//28
		ITEM_TYPE_DS,					//29
		ITEM_TYPE_SPECIAL_DS,			//30
		ITEM_TYPE_EXTRACT,				//31
		ITEM_TYPE_SECONDARY_COIN,		//32
		ITEM_TYPE_RING,					//33
		ITEM_TYPE_BELT,					//34
		ITEM_TYPE_PET,					//35
		ITEM_TYPE_MEDIUM,				//36	ENABLE_MOVE_COSTUME_ATTR
		ITEM_TYPE_GACHA,				//37	ENABLE_BATTLE_FIELD
		ITEM_TYPE_SOUL,					//38	ENABLE_SOUL_SYSTEM
		ITEM_TYPE_PASSIVE,				//39	ENABLE_PASSIVE_SYSTEM
		ITEM_TYPE_MERCENARY,			//40

		ITEM_TYPE_MAX_NUM
	};

	enum EResourceSubTypes
	{
		RESOURCE_FISHBONE,
		RESOURCE_WATERSTONEPIECE,
		RESOURCE_WATERSTONE,
		RESOURCE_BLOOD_PEARL,
		RESOURCE_BLUE_PEARL,
		RESOURCE_WHITE_PEARL,
		RESOURCE_BUCKET,
		RESOURCE_CRYSTAL,
		RESOURCE_GEM,
		RESOURCE_STONE,
		RESOURCE_METIN,
		RESOURCE_ORE,
		RESOURCE_AURA	//ENABLE_AURA_SYSTEM
	};

#if defined(ENABLE_PROTO_RENEWAL) || defined(ENABLE_MOVE_COSTUME_ATTR)
	enum EMediumSubTypes
	{
		MEDIUM_MOVE_COSTUME_ATTR = 0
	};
#endif

#if defined(ENABLE_PROTO_RENEWAL) || defined(ENABLE_BATTLE_FIELD)
	enum EGachaSubTypes
	{
		USE_GACHA,
		GEM_LUCKY_BOX_GACHA,
		SPECIAL_LUCKY_BOX_GACHA
	};
#endif

#ifdef ENABLE_AURA_SYSTEM
	enum EAuraGradeType
	{
		AURA_GRADE_NONE,
		AURA_GRADE_ORDINARY,
		AURA_GRADE_SIMPLE,
		AURA_GRADE_NOBLE,
		AURA_GRADE_SPARKLING,
		AURA_GRADE_MAGNIFICENT,
		AURA_GRADE_RADIANT,
		AURA_GRADE_MAX_NUM,
	};
	enum EAuraItem
	{
		AURA_BOOST_ITEM_VNUM_BASE = 49980
	};
	enum EAuraBoostIndex
	{
		ITEM_AURA_BOOST_ERASER,
		ITEM_AURA_BOOST_WEAK,
		ITEM_AURA_BOOST_NORMAL,
		ITEM_AURA_BOOST_STRONG,
		ITEM_AURA_BOOST_ULTIMATE,
		ITEM_AURA_BOOST_MAX,
	};
#endif

	enum EWeddingItem
	{
		WEDDING_TUXEDO1 = 11901,
		WEDDING_TUXEDO2 = 11902,
		WEDDING_BRIDE_DRESS1 = 11903,
		WEDDING_BRIDE_DRESS2 = 11904,
		WEDDING_TUXEDO3 = 11911,
		WEDDING_TUXEDO4 = 11912,
		WEDDING_BRIDE_DRESS3 = 11913,
		WEDDING_BRIDE_DRESS4 = 11914,
		WEDDING_BOUQUET1 = 50201,
		WEDDING_BOUQUET2 = 50202,
	};

	enum EWeaponSubTypes
	{
		WEAPON_SWORD,
		WEAPON_DAGGER,
		WEAPON_BOW,
		WEAPON_TWO_HANDED,
		WEAPON_BELL,
		WEAPON_FAN,
		WEAPON_ARROW,
		WEAPON_MOUNT_SPEAR,
		WEAPON_CLAW,	//ENABLE_WOLFMAN_CHARACTER
		WEAPON_QUIVER,	//ENABLE_QUIVER_SYSTEM
		WEAPON_BOUQUET,
		WEAPON_NUM_TYPES, //11 2015/11/12

		WEAPON_NONE = WEAPON_NUM_TYPES + 1
	};

	enum EMaterialSubTypes
	{
		MATERIAL_LEATHER,
		MATERIAL_BLOOD,
		MATERIAL_ROOT,
		MATERIAL_NEEDLE,
		MATERIAL_JEWEL,
		MATERIAL_DS_REFINE_NORMAL,
		MATERIAL_DS_REFINE_BLESSED,
		MATERIAL_DS_REFINE_HOLLY,
#ifdef ENABLE_PROTO_RENEWAL
		MATERIAL_DS_CHANGE_ATTR,
		MATERIAL_PASSIVE_WEAPON,
		MATERIAL_PASSIVE_ARMOR,
		MATERIAL_PASSIVE_ACCE,
		MATERIAL_PASSIVE_ELEMENT,
		UNK5_13,
		UNK5_14,
		UNK5_15,
		UNK5_16,
		UNK5_17,
		UNK5_18,
		UNK5_19,
		UNK5_20,
		UNK5_21,
		UNK5_22,
		UNK5_23,
		UNK5_24,
		UNK5_25,
		UNK5_26,
		UNK5_27,
		UNK5_28,
		UNK5_29,
		UNK5_30,
		UNK5_31,
		UNK5_32,
		UNK5_33,
		UNK5_34,
		UNK5_35,
		UNK5_36,
		UNK5_37,
		UNK5_38,
		UNK5_39
#endif
	};

	enum EArmorSubTypes
	{
		ARMOR_BODY,
		ARMOR_HEAD,
		ARMOR_SHIELD,
		ARMOR_WRIST,
		ARMOR_FOOTS,
		ARMOR_NECK,
		ARMOR_EAR,
		ARMOR_PENDANT,	//ENABLE_PENDANT
#ifdef ENABLE_GLOVE_SYSTEM
		ARMOR_GLOVE,
#endif
		ARMOR_NUM_TYPES
	};

	enum ECostumeSubTypes
	{
		COSTUME_BODY,	//0
		COSTUME_HAIR,	//1
		COSTUME_MOUNT,	//2	ENABLE_MOUNT_COSTUME_SYSTEM
		COSTUME_ACCE,	//3	ENABLE_ACCE_COSTUME_SYSTEM
		COSTUME_WEAPON,	//4	ENABLE_WEAPON_COSTUME_SYSTEM
		COSTUME_AURA,	//5	ENABLE_AURA_SYSTEM
		COSTUME_NUM_TYPES
	};

	enum EUseSubTypes
	{
		USE_POTION,						// 0
		USE_TALISMAN,					// 1
		USE_TUNING,						// 2
		USE_MOVE,						// 3
		USE_TREASURE_BOX,				// 4
		USE_MONEYBAG,					// 5
		USE_BAIT,						// 6
		USE_ABILITY_UP,					// 7
		USE_AFFECT,						// 8
		USE_CREATE_STONE,				// 9
		USE_SPECIAL,					// 10
		USE_POTION_NODELAY,				// 11
		USE_CLEAR,						// 12
		USE_INVISIBILITY,				// 13
		USE_DETACHMENT,					// 14
		USE_BUCKET,						// 15
		USE_POTION_CONTINUE,			// 16
		USE_CLEAN_SOCKET,				// 17
		USE_CHANGE_ATTRIBUTE,			// 18
		USE_ADD_ATTRIBUTE,				// 19
		USE_ADD_ACCESSORY_SOCKET,		// 20
		USE_PUT_INTO_ACCESSORY_SOCKET,	// 21
		USE_ADD_ATTRIBUTE2,				// 22
		USE_RECIPE,						// 23
		USE_CHANGE_ATTRIBUTE2,			// 24
		USE_BIND,						// 25
		USE_UNBIND,						// 26
		USE_TIME_CHARGE_PER,			// 27
		USE_TIME_CHARGE_FIX,			// 28
		USE_PUT_INTO_BELT_SOCKET,		// 29
		USE_PUT_INTO_RING_SOCKET,		// 30
		USE_CHANGE_COSTUME_ATTR,		// 31	ENABLE_USE_COSTUME_ATTR
		USE_RESET_COSTUME_ATTR,			// 32	ENABLE_USE_COSTUME_ATTR
#ifdef ENABLE_PROTO_RENEWAL
		USE_UNK_33,						// 33
		USE_SELECT_ATTRIBUTE,			// 34	ENABLE_CHANGED_ATTR
		USE_FLOWER,						// 35	ENABLE_FLOWER_EVENT
		USE_EMOTION_PACK,				// 36	ENABLE_EXPRESSING_EMOTION
		USE_ELEMENT_UPGRADE,			// 37	ENABLE_REFINE_ELEMENT
		USE_ELEMENT_DOWNGRADE,			// 38	ENABLE_REFINE_ELEMENT
		USE_ELEMENT_CHANGE,				// 39	ENABLE_REFINE_ELEMENT
		USE_CALL,						// 40
		USE_POTION_TOWER,				// 41
		USE_POTION_NODELAY_TOWER,		// 42
		USE_REMOVE_AFFECT,				// 43
		USE_EMOTION_TOWER,				// 44
		USE_SECRET_DUNGEON_SCROLL,		// 45
#endif

		// Custom
		USE_AGGREGATE_MONSTER,
#if defined(ENABLE_AURA_SYSTEM) && defined(ENABLE_AURA_BOOST)
		USE_PUT_INTO_AURA_SOCKET,		// AURA_BOOSTER
#endif
	};

	enum ESoulSubType
	{
		SOUL_RED,
		SOUL_BLUE,
	};

	enum EDragonSoulSubType
	{
		DS_SLOT1,
		DS_SLOT2,
		DS_SLOT3,
		DS_SLOT4,
		DS_SLOT5,
		DS_SLOT6,
		DS_SLOT_NUM_TYPES = 6
	};

	enum EExtractSubTypes
	{
		EXTRACT_DRAGON_SOUL,
		EXTRACT_DRAGON_HEART,
	};

	enum EMetinSubTypes
	{
		METIN_NORMAL,
		METIN_GOLD,
#if defined(ENABLE_PROTO_RENEWAL) && defined(ENABLE_YOHARA_SYSTEM)
		METIN_SUNGMA,
#endif
	};

	enum ELimitTypes
	{
		LIMIT_NONE,

		LIMIT_LEVEL,
		LIMIT_STR,
		LIMIT_DEX,
		LIMIT_INT,
		LIMIT_CON,
#ifndef ENABLE_PROTO_RENEWAL
		LIMIT_PCBANG,
#endif
		LIMIT_REAL_TIME,
		LIMIT_REAL_TIME_START_FIRST_USE,
		LIMIT_TIMER_BASED_ON_WEAR,
#ifdef ENABLE_PROTO_RENEWAL
		LIMIT_NEWWORLD_LEVEL,
		LIMIT_DURATION,
#endif
		LIMIT_MAX_NUM
	};

	enum EItemAntiFlag
	{
		ITEM_ANTIFLAG_FEMALE		= (1 << 0),
		ITEM_ANTIFLAG_MALE			= (1 << 1),
		ITEM_ANTIFLAG_WARRIOR		= (1 << 2),
		ITEM_ANTIFLAG_ASSASSIN		= (1 << 3),
		ITEM_ANTIFLAG_SURA			= (1 << 4),
		ITEM_ANTIFLAG_SHAMAN		= (1 << 5),
		ITEM_ANTIFLAG_GET			= (1 << 6),
		ITEM_ANTIFLAG_DROP			= (1 << 7),
		ITEM_ANTIFLAG_SELL			= (1 << 8),
		ITEM_ANTIFLAG_EMPIRE_A		= (1 << 9),
		ITEM_ANTIFLAG_EMPIRE_B		= (1 << 10),
		ITEM_ANTIFLAG_EMPIRE_R		= (1 << 11),
		ITEM_ANTIFLAG_SAVE			= (1 << 12),
		ITEM_ANTIFLAG_GIVE			= (1 << 13),
		ITEM_ANTIFLAG_PKDROP		= (1 << 14),
		ITEM_ANTIFLAG_STACK			= (1 << 15),
		ITEM_ANTIFLAG_MYSHOP		= (1 << 16),
		ITEM_ANTIFLAG_SAFEBOX		= (1 << 17),
		ITEM_ANTIFLAG_WOLFMAN		= (1 << 18),	// ENABLE_WOLFMAN_CHARACTER
#ifdef ENABLE_PROTO_RENEWAL
		ITEM_ANTIFLAG_RT_REMOVE		= (1 << 19),
		ITEM_ANTIFLAG_QUICKSLOT		= (1 << 20),	//ENABLE_ANTI_QUICKSLOT
		ITEM_ANTIFLAG_CHANGELOOK	= (1 << 21),	//ENABLE_CHANGELOOK_SYSTEM
		ITEM_ANTIFLAG_REINFORCE		= (1 << 22),
		ITEM_ANTIFLAG_ENCHANT		= (1 << 23),
		ITEM_ANTIFLAG_ENERGY		= (1 << 24),
		ITEM_ANTIFLAG_PETFEED		= (1 << 25),	//ENABLE_GROWTH_PET_SYSTEM
		ITEM_ANTIFLAG_APPLY			= (1 << 26),
		ITEM_ANTIFLAG_ACCE			= (1 << 27),	//ENABLE_ACCE_COSTUME_SYSTEM
		ITEM_ANTIFLAG_MAIL			= (1 << 28),	//ENABLE_MAILBOX
#endif
	};

	enum EItemFlag
	{
		ITEM_FLAG_REFINEABLE		= (1 << 0),
		ITEM_FLAG_SAVE				= (1 << 1),
		ITEM_FLAG_STACKABLE			= (1 << 2),
		ITEM_FLAG_COUNT_PER_1GOLD	= (1 << 3),
		ITEM_FLAG_SLOW_QUERY		= (1 << 4),
		ITEM_FLAG_UNIQUE			= (1 << 5),		// UNUSED
		ITEM_FLAG_MAKECOUNT			= (1 << 6),
		ITEM_FLAG_IRREMOVABLE		= (1 << 7),
		ITEM_FLAG_CONFIRM_WHEN_USE	= (1 << 8),
		ITEM_FLAG_QUEST_USE			= (1 << 9),
		ITEM_FLAG_QUEST_USE_MULTIPLE = (1 << 10),
		ITEM_FLAG_QUEST_GIVE		= (1 << 11),	// UNUSED
		ITEM_FLAG_LOG				= (1 << 12),
		ITEM_FLAG_APPLICABLE		= (1 << 13),	// UNUSED
		ITEM_FLAG_GROUP_DMG_WEAPON	= (1 << 14),	// ENABLE_GROUP_DAMAGE_WEAPON_EFFECT
	};

	enum EWearPositions
	{
		WEAR_BODY,					// 0
		WEAR_HEAD,					// 1
		WEAR_FOOTS,					// 2
		WEAR_WRIST,					// 3
		WEAR_WEAPON,				// 4
		WEAR_NECK,					// 5
		WEAR_EAR,					// 6
		WEAR_SHIELD,				// 10
		WEAR_UNIQUE1,				// 7
		WEAR_UNIQUE2,				// 8
		WEAR_ARROW,					// 9
		WEAR_ABILITY1,				// 11
		WEAR_ABILITY2,				// 12
		WEAR_ABILITY3,				// 13
		WEAR_ABILITY4,				// 14
		WEAR_ABILITY5,				// 15
		WEAR_ABILITY6,				// 16
		WEAR_ABILITY7,				// 17
		WEAR_ABILITY8,				// 18
		WEAR_COSTUME_BODY,			// 19
		WEAR_COSTUME_HAIR,			// 20
		WEAR_COSTUME_MOUNT,			// 21	ENABLE_MOUNT_COSTUME_SYSTEM
		WEAR_COSTUME_ACCE,			// 22	ENABLE_ACCE_COSTUME_SYSTEM
		WEAR_COSTUME_WEAPON,		// 23	ENABLE_WEAPON_COSTUME_SYSTEM
		WEAR_COSTUME_AURA,			// 24	ENABLE_AURA_SYSTEM
		WEAR_RING1,					// 25
		WEAR_RING2,					// 26
		WEAR_BELT,					// 27
		WEAR_PENDANT,				// 28	ENABLE_PENDANT
#ifdef ENABLE_GLOVE_SYSTEM
		WEAR_GLOVE,					// 29
#endif
#ifdef ENABLE_PASSIVE_SYSTEM
		WEAR_PASSIVE_ATTR_UP,		// 30
		WEAR_PASSIVE_ATTR_DOWN,		// 31
#endif
#if defined(ENABLE_PROTO_RENEWAL_CUSTOM) && defined(ENABLE_PET_SYSTEM)
		WEAR_PET,
		WEAR_MAX_NUM = 33
#else
		WEAR_MAX_NUM = 32
#endif
	};

	enum EItemWearableFlag
	{
		WEARABLE_BODY       = (1 << 0),	// 1
		WEARABLE_HEAD       = (1 << 1),	// 2
		WEARABLE_FOOTS      = (1 << 2),	// 4
		WEARABLE_WRIST      = (1 << 3),	// 8
		WEARABLE_WEAPON     = (1 << 4),	// 16
		WEARABLE_NECK       = (1 << 5),	// 32
		WEARABLE_EAR        = (1 << 6),	// 64
		WEARABLE_SHIELD     = (1 << 7),	// 128
		WEARABLE_UNIQUE     = (1 << 8),	// 256
		WEARABLE_ARROW      = (1 << 9),	// 512
		WEARABLE_HAIR		= (1 << 10),// 1024
		WEARABLE_ABILITY	= (1 << 11),// 2048
		WEARABLE_PENDANT	= (1 << 12),// 4096	ENABLE_PENDANT
#ifdef ENABLE_GLOVE_SYSTEM
		WEARABLE_GLOVE		= (1 << 13),// 8192
#endif
	};

	enum EApplyTypes
	{
		APPLY_NONE,						// 0	- POINT_NONE,	0	Kein Bonus
		APPLY_MAX_HP,					// 1	- POINT_MAX_HP,	6	Max TP
		APPLY_MAX_SP,					// 2	- POINT_MAX_SP,	8	Max MP
		APPLY_CON,						// 3	- POINT_HT,	13	Vitalit‰t
		APPLY_INT,						// 4	- POINT_IQ,	15	Intelligenz
		APPLY_STR,						// 5	- POINT_ST,	12		St‰rke
		APPLY_DEX,						// 6	- POINT_DX,	14	Beweglichkeit
		APPLY_ATT_SPEED,				// 7	- POINT_ATT_SPEED,	17	Angriffsgeschwindigkeit
		APPLY_MOV_SPEED,				// 8	- POINT_MOV_SPEED,	19	Bewegungsgeschwindigkeit
		APPLY_CAST_SPEED,				// 9	- POINT_CASTING_SPEED,	21	Zaubergeschwindigkeit
		APPLY_HP_REGEN,					// 10	- POINT_HP_REGEN,	32	TP-Regeneration
		APPLY_SP_REGEN,					// 11	- POINT_SP_REGEN,	33	MP-Regeneration
		APPLY_POISON_PCT,				// 12	- POINT_POISON_PCT,	37	Vergiftungschance
		APPLY_STUN_PCT,					// 13	- POINT_STUN_PCT,	38	Ohnmachtchance
		APPLY_SLOW_PCT,					// 14	- POINT_SLOW_PCT,	39	Verlangsamungschance
		APPLY_CRITICAL_PCT,				// 15	- POINT_CRITICAL_PCT,	40	Kritische Treffer Chance
		APPLY_PENETRATE_PCT,			// 16	- POINT_PENETRATE_PCT,	41	x
		APPLY_ATTBONUS_HUMAN,			// 17	- POINT_ATTBONUS_HUMAN,	43	Stark gegen Halbmenschen
		APPLY_ATTBONUS_ANIMAL,			// 18	- POINT_ATTBONUS_ANIMAL,	44	Stark gegen Tiere
		APPLY_ATTBONUS_ORC,				// 19	- POINT_ATTBONUS_ORC,	45	Stark gegen Orks
		APPLY_ATTBONUS_MILGYO,			// 20	- POINT_ATTBONUS_MILGYO,	46	Stark gegen Esoterische
		APPLY_ATTBONUS_UNDEAD,			// 21	- POINT_ATTBONUS_UNDEAD,	47	Stark gegen Untote
		APPLY_ATTBONUS_DEVIL,			// 22	- POINT_ATTBONUS_DEVIL,	48	Stark gegen Teufel
		APPLY_STEAL_HP,					// 23	- POINT_STEAL_HP,	63	Chance auf TP Raub
		APPLY_STEAL_SP,					// 24	- POINT_STEAL_SP,	64	Chance auf MP Raub
		APPLY_MANA_BURN_PCT,			// 25	- POINT_MANA_BURN_PCT,	65	Verbrennungschance
		APPLY_DAMAGE_SP_RECOVER,		// 26	- POINT_DAMAGE_SP_RECOVER,	66	x
		APPLY_BLOCK,					// 27	- POINT_BLOCK,	67	Chance auf Abblocken
		APPLY_DODGE,					// 28	- POINT_DODGE,	68	Chance auf Refkeltieren
		APPLY_RESIST_SWORD,				// 29	- POINT_RESIST_SWORD,	69	Schwertverteidigung
		APPLY_RESIST_TWOHAND,			// 30	- POINT_RESIST_TWOHAND,	70	Zweihandverteidigung
		APPLY_RESIST_DAGGER,			// 31	- POINT_RESIST_DAGGER,	71	Dolchverteidigung
		APPLY_RESIST_BELL,				// 32	- POINT_RESIST_BELL,	72	Glockenverteidigung
		APPLY_RESIST_FAN,				// 33	- POINT_RESIST_FAN,	73		F‰cherverteidigung
		APPLY_RESIST_BOW,				// 34	- POINT_RESIST_BOW,	74	Pfeilwiderstand
		APPLY_RESIST_FIRE,				// 35	- POINT_RESIST_FIRE,	75	Feuerresistenz
		APPLY_RESIST_ELEC,				// 36	- POINT_RESIST_ELEC,	76	Blitzresistenz
		APPLY_RESIST_MAGIC,				// 37	- POINT_RESIST_MAGIC,	77	Magiewiderstand
		APPLY_RESIST_WIND,				// 38	- POINT_RESIST_WIND,	78		Windwiderstand
		APPLY_REFLECT_MELEE,			// 39	- POINT_REFLECT_MELEE,	79	x
		APPLY_REFLECT_CURSE,			// 40	- POINT_REFLECT_CURSE,	80	x
		APPLY_POISON_REDUCE,			// 41	- POINT_POISON_REDUCE,	81	Giftwiederstand
		APPLY_KILL_SP_RECOVER,			// 42	- POINT_KILL_SP_RECOVER,	82	Chance MP Wiederherzustellen
		APPLY_EXP_DOUBLE_BONUS,			// 43	- POINT_EXP_DOUBLE_BONUS,	83	Chance auf Doppelte EXP
		APPLY_GOLD_DOUBLE_BONUS,		// 44	- POINT_GOLD_DOUBLE_BONUS,	84		Chance auf Yangbonus
		APPLY_ITEM_DROP_BONUS,			// 45	- POINT_ITEM_DROP_BONUS,	85	Chance mehr Gegenst‰nde zu Droppen
		APPLY_POTION_BONUS,				// 46	- POINT_POTION_BONUS,	86	x
		APPLY_KILL_HP_RECOVER,			// 47	- POINT_KILL_HP_RECOVERY,	87	Chance TP Wiederherzustellen
		APPLY_IMMUNE_STUN,				// 48	- POINT_IMMUNE_STUN,	88	Abwehr gegen Ohnmacht
		APPLY_IMMUNE_SLOW,				// 49	- POINT_IMMUNE_SLOW,	89	Abwehr gegen Verlangsamen
		APPLY_IMMUNE_FALL,				// 50	- POINT_IMMUNE_FALL,	90	x
		APPLY_SKILL,					// 51	- POINT_NONE,	0	x
		APPLY_BOW_DISTANCE,				// 52	- POINT_BOW_DISTANCE,	34	x
		APPLY_ATT_GRADE_BONUS,			// 53	- POINT_ATT_GRADE_BONUS,	95		Angriffswert
		APPLY_DEF_GRADE_BONUS,			// 54	- POINT_DEF_GRADE_BONUS,	96	x
		APPLY_MAGIC_ATT_GRADE,			// 55	- POINT_MAGIC_ATT_GRADE_BONUS,	97	x
		APPLY_MAGIC_DEF_GRADE,			// 56	- POINT_MAGIC_DEF_GRADE_BONUS,	98	x
		APPLY_CURSE_PCT,				// 57	- POINT_CURSE_PCT,	42	Chance jemanden zu Verfluchen
		APPLY_MAX_STAMINA,				// 58	- POINT_MAX_STAMINA,	10	Max Ausdauer
		APPLY_ATT_BONUS_TO_WARRIOR,			// 59	- POINT_ATTBONUS_WARRIOR,	54	Stark gegen Krieger
		APPLY_ATT_BONUS_TO_ASSASSIN,		// 60	- POINT_ATTBONUS_ASSASSIN,	55	Stark gegen Ninja
		APPLY_ATT_BONUS_TO_SURA,			// 61	- POINT_ATTBONUS_SURA,	56	Stark gegen Sura
		APPLY_ATT_BONUS_TO_SHAMAN,			// 62	- POINT_ATTBONUS_SHAMAN,	57	Stark gegen Schamanen
		APPLY_ATT_BONUS_TO_MONSTER,			// 63	- POINT_ATTBONUS_MONSTER,	53	x
		APPLY_MALL_ATTBONUS,			// 64	- POINT_ATT_BONUS,	93	x
		APPLY_MALL_DEFBONUS,			// 65	- POINT_MALL_DEFBONUS,	115	Nahkampfttrefferwiderstand
		APPLY_MALL_EXPBONUS,			// 66	- POINT_MALL_EXPBONUS,	116	x
		APPLY_MALL_ITEMBONUS,			// 67	- POINT_MALL_ITEMBONUS,	117	x
		APPLY_MALL_GOLDBONUS,			// 68	- POINT_MALL_GOLDBONUS,	118	x
		APPLY_MAX_HP_PCT,				// 69	- POINT_MAX_HP_PCT,	119	x
		APPLY_MAX_SP_PCT,				// 70	- POINT_MAX_SP_PCT,	120	x
		APPLY_SKILL_DAMAGE_BONUS,		// 71	- POINT_SKILL_DAMAGE_BONUS,	121	Fertigkeitsschaden (FKS)
		APPLY_NORMAL_HIT_DAMAGE_BONUS,	// 72	- POINT_NORMAL_HIT_DAMAGE_BONUS,	122	Durchschnittlicher Schaden (DSS)
		APPLY_SKILL_DEFEND_BONUS,		// 73	- POINT_SKILL_DEFEND_BONUS,	123		Fertigkeitwiderstand
		APPLY_NORMAL_HIT_DEFEND_BONUS,	// 74	- POINT_NORMAL_HIT_DEFEND_BONUS,	124	Dursch. Schadenswiderstand
		APPLY_EXTRACT_HP_PCT,			// 75	- POINT_NONE,	0	x
		APPLY_PC_BANG_EXP_BONUS,		// 76	- POINT_PC_BANG_EXP_BONUS,	125	x
		APPLY_PC_BANG_DROP_BONUS,		// 77	- POINT_PC_BANG_DROP_BONUS,	126	x
		APPLY_RESIST_WARRIOR,			// 78	- POINT_RESIST_WARRIOR,	59	Abwehr gegen Krieger
		APPLY_RESIST_ASSASSIN,			// 79	- POINT_RESIST_ASSASSIN,	60	Abwehr gegen Ninja
		APPLY_RESIST_SURA,				// 80	- POINT_RESIST_SURA,	61		Abwehr gegen Sura
		APPLY_RESIST_SHAMAN,			// 81	- POINT_RESIST_SHAMAN,	62	Abwehr gegen Schamanen
		APPLY_ENERGY,					// 82	- POINT_ENERGY,	128	x
		APPLY_DEF_GRADE,				// 83	- POINT_DEF_GRADE,	16	x
		APPLY_COSTUME_ATTR_BONUS,		// 84	- POINT_COSTUME_ATTR_BONUS,	130	x
		APPLY_MAGIC_ATTBONUS_PER,		// 85	- POINT_MAGIC_ATT_BONUS_PER,	131	x
		APPLY_MELEE_MAGIC_ATTBONUS_PER,	// 86	- POINT_MELEE_MAGIC_ATT_BONUS_PER,	132	Magietrefferwiderstand in %
		APPLY_RESIST_ICE,				// 87	- POINT_RESIST_ICE,	133	x
		APPLY_RESIST_EARTH,				// 88	- POINT_RESIST_EARTH,	134	x
		APPLY_RESIST_DARK,				// 89	- POINT_RESIST_DARK,	135	x
		APPLY_ANTI_CRITICAL_PCT,		// 90	- POINT_RESIST_CRITICAL,	136	x
		APPLY_ANTI_PENETRATE_PCT,		// 91	- POINT_RESIST_PENETRATE,	137	x
		APPLY_BLEEDING_REDUCE,			// 92	- POINT_BLEEDING_REDUCE,	138	Widerstand gegen Blutungsangriff
		APPLY_BLEEDING_PCT,				// 93	- POINT_BLEEDING_PCT,	139	Blutungsangriff
		APPLY_ATT_BONUS_TO_WOLFMAN,			// 94	- POINT_ATTBONUS_WOLFMAN,	140	Stark gegen Wolfman
		APPLY_RESIST_WOLFMAN,			// 95	- POINT_RESIST_WOLFMAN,	141	Abwehrchance gegen Lykaner
		APPLY_RESIST_CLAW,				// 96	- POINT_RESIST_CLAW,	142	Krallenwiderstand
		APPLY_ACCEDRAIN_RATE,			// 97	- POINT_ACCEDRAIN_RATE,	143	Aufnahmegrad
		APPLY_RESIST_MAGIC_REDUCTION,	// 98	- POINT_RESIST_MAGIC_REDUCTION,	144	Magiebruch
		APPLY_ENCHANT_ELECT,
		APPLY_ENCHANT_FIRE,
		APPLY_ENCHANT_ICE,
		APPLY_ENCHANT_WIND,
		APPLY_ENCHANT_EARTH,
		APPLY_ENCHANT_DARK,
		APPLY_ATTBONUS_CZ,
		APPLY_ATTBONUS_INSECT,
		APPLY_ATTBONUS_DESERT,
		APPLY_ATTBONUS_SWORD,
		APPLY_ATTBONUS_TWOHAND,
		APPLY_ATTBONUS_DAGGER,
		APPLY_ATTBONUS_BELL,
		APPLY_ATTBONUS_FAN,
		APPLY_ATTBONUS_BOW,
		APPLY_ATTBONUS_CLAW,
		APPLY_RESIST_HUMAN,
		APPLY_RESIST_MOUNT_FALL,
		APPLY_RESIST_FIST,
		APPLY_MOUNT,
#ifdef ENABLE_ATTR_6TH_7TH_EXTEND
		APPLY_SKILL_DAMAGE_SAMYEON = 119,
		APPLY_SKILL_DAMAGE_TANHWAN = 120,
		APPLY_SKILL_DAMAGE_PALBANG = 121,
		APPLY_SKILL_DAMAGE_GIGONGCHAM = 122,
		APPLY_SKILL_DAMAGE_GYOKSAN = 123,
		APPLY_SKILL_DAMAGE_GEOMPUNG = 124,
		APPLY_SKILL_DAMAGE_AMSEOP = 125,
		APPLY_SKILL_DAMAGE_GUNGSIN = 126,
		APPLY_SKILL_DAMAGE_CHARYUN = 127,
		APPLY_SKILL_DAMAGE_SANGONG = 128,
		APPLY_SKILL_DAMAGE_YEONSA = 129,
		APPLY_SKILL_DAMAGE_KWANKYEOK = 130,
		APPLY_SKILL_DAMAGE_GIGUNG = 131,
		APPLY_SKILL_DAMAGE_HWAJO = 132,
		APPLY_SKILL_DAMAGE_SWAERYUNG = 133,
		APPLY_SKILL_DAMAGE_YONGKWON = 134,
		APPLY_SKILL_DAMAGE_PABEOB = 135,
		APPLY_SKILL_DAMAGE_MARYUNG = 136,
		APPLY_SKILL_DAMAGE_HWAYEOMPOK = 137,
		APPLY_SKILL_DAMAGE_MAHWAN = 138,
		APPLY_SKILL_DAMAGE_BIPABU = 139,
		APPLY_SKILL_DAMAGE_YONGBI = 140,
		APPLY_SKILL_DAMAGE_PAERYONG = 141,
		APPLY_SKILL_DAMAGE_NOEJEON = 142,
		APPLY_SKILL_DAMAGE_BYEURAK = 143,
		APPLY_SKILL_DAMAGE_CHAIN = 144,
		APPLY_SKILL_DAMAGE_CHAYEOL = 145,
		APPLY_SKILL_DAMAGE_SALPOONG = 146,
		APPLY_SKILL_DAMAGE_GONGDAB = 147,
		APPLY_SKILL_DAMAGE_PASWAE = 148,
		APPLY_NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE = 149,
		APPLY_SKILL_DEFEND_BONUS_BOSS_OR_MORE = 150,
		APPLY_NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE = 151,
		APPLY_SKILL_DAMAGE_BONUS_BOSS_OR_MORE = 152,
		APPLY_HIT_BUFF_ENCHANT_FIRE = 153,
		APPLY_HIT_BUFF_ENCHANT_ICE = 154,
		APPLY_HIT_BUFF_ENCHANT_ELEC = 155,
		APPLY_HIT_BUFF_ENCHANT_WIND = 156,
		APPLY_HIT_BUFF_ENCHANT_DARK = 157,
		APPLY_HIT_BUFF_ENCHANT_EARTH = 158,
		APPLY_HIT_BUFF_RESIST_FIRE = 159,
		APPLY_HIT_BUFF_RESIST_ICE = 160,
		APPLY_HIT_BUFF_RESIST_ELEC = 161,
		APPLY_HIT_BUFF_RESIST_WIND = 162,
		APPLY_HIT_BUFF_RESIST_DARK = 163,
		APPLY_HIT_BUFF_RESIST_EARTH = 164,
		APPLY_USE_SKILL_CHEONGRANG_MOV_SPEED = 165,
		APPLY_USE_SKILL_CHEONGRANG_CASTING_SPEED = 166,
		APPLY_USE_SKILL_CHAYEOL_CRITICAL_PCT = 167,
		APPLY_USE_SKILL_SANGONG_ATT_GRADE_BONUS = 168,
		APPLY_USE_SKILL_GIGUNG_ATT_GRADE_BONUS = 169,
		APPLY_USE_SKILL_JEOKRANG_DEF_BONUS = 170,
		APPLY_USE_SKILL_GWIGEOM_DEF_BONUS = 171,
		APPLY_USE_SKILL_TERROR_ATT_GRADE_BONUS = 172,
		APPLY_USE_SKILL_MUYEONG_ATT_GRADE_BONUS = 173,
		APPLY_USE_SKILL_MANASHILED_CASTING_SPEED = 174,
		APPLY_USE_SKILL_HOSIN_DEF_BONUS = 175,
		APPLY_USE_SKILL_GICHEON_ATT_GRADE_BONUS = 176,
		APPLY_USE_SKILL_JEONGEOP_ATT_GRADE_BONUS = 177,
		APPLY_USE_SKILL_JEUNGRYEOK_DEF_BONUS = 178,
		APPLY_USE_SKILL_GIHYEOL_ATT_GRADE_BONUS = 179,
		APPLY_USE_SKILL_CHUNKEON_CASTING_SPEED = 180,
		APPLY_USE_SKILL_NOEGEOM_ATT_GRADE_BONUS = 181,
		APPLY_SKILL_DURATION_INCREASE_EUNHYUNG = 182,
		APPLY_SKILL_DURATION_INCREASE_GYEONGGONG = 183,
		APPLY_SKILL_DURATION_INCREASE_GEOMKYUNG = 184,
		APPLY_SKILL_DURATION_INCREASE_JEOKRANG = 185,
		APPLY_USE_SKILL_PALBANG_HP_ABSORB = 186,
		APPLY_USE_SKILL_AMSEOP_HP_ABSORB = 187,
		APPLY_USE_SKILL_YEONSA_HP_ABSORB = 188,
		APPLY_USE_SKILL_YONGBI_HP_ABSORB = 189,
		APPLY_USE_SKILL_CHAIN_HP_ABSORB = 190,
		APPLY_USE_SKILL_PASWAE_SP_ABSORB = 191,
		APPLY_USE_SKILL_GIGONGCHAM_STUN = 192,
		APPLY_USE_SKILL_CHARYUN_STUN = 193,
		APPLY_USE_SKILL_PABEOB_STUN = 194,
		APPLY_USE_SKILL_MAHWAN_STUN = 195,
		APPLY_USE_SKILL_GONGDAB_STUN = 196,
		APPLY_USE_SKILL_SAMYEON_STUN = 197,
		APPLY_USE_SKILL_GYOKSAN_KNOCKBACK = 198,
		APPLY_USE_SKILL_SEOMJEON_KNOCKBACK = 199,
		APPLY_USE_SKILL_SWAERYUNG_KNOCKBACK = 200,
		APPLY_USE_SKILL_HWAYEOMPOK_KNOCKBACK = 201,
		APPLY_USE_SKILL_GONGDAB_KNOCKBACK = 202,
		APPLY_USE_SKILL_KWANKYEOK_KNOCKBACK = 203,
		APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_10PER = 204,
		APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_10PER = 205,
		APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_10PER = 206,
		APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_10PER = 207,
		APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_10PER = 208,
		APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_10PER = 209,
		APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_10PER = 210,
		APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_10PER = 211,
		APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_10PER = 212,
		APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_10PER = 213,
		APPLY_ATTBONUS_STONE = 214,
		APPLY_DAMAGE_HP_RECOVERY = 215,
		APPLY_DAMAGE_SP_RECOVERY = 216,
		APPLY_ALIGNMENT_DAMAGE_BONUS = 217,
		APPLY_NORMAL_DAMAGE_GUARD = 218,
		APPLY_MORE_THEN_HP90_DAMAGE_REDUCE = 219,
		APPLY_USE_SKILL_TUSOK_HP_ABSORB = 220,
		APPLY_USE_SKILL_PAERYONG_HP_ABSORB = 221,
		APPLY_USE_SKILL_BYEURAK_HP_ABSORB = 222,
		APPLY_FIRST_ATTRIBUTE_BONUS = 223,
		APPLY_SECOND_ATTRIBUTE_BONUS = 224,
		APPLY_THIRD_ATTRIBUTE_BONUS = 225,
		APPLY_FOURTH_ATTRIBUTE_BONUS = 226,
		APPLY_FIFTH_ATTRIBUTE_BONUS = 227,
		APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_20PER = 228,
		APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_20PER = 229,
		APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_20PER = 230,
		APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_20PER = 231,
		APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_20PER = 232,
		APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_20PER = 233,
		APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_20PER = 234,
		APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_20PER = 235,
		APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_20PER = 236,
		APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_20PER = 237,
		APPLY_USE_SKILL_CHAYEOL_HP_ABSORB = 238,
		APPLY_SUNGMA_STR = 239,
		APPLY_SUNGMA_HP = 240,
		APPLY_SUNGMA_MOVE = 241,
		APPLY_SUNGMA_IMMUNE = 242,
		APPLY_HIT_PCT = 243,
		APPLY_RANDOM = 244,
		APPLY_ATTBONUS_PER_HUMAN = 245,
		APPLY_ATTBONUS_PER_ANIMAL = 246,
		APPLY_ATTBONUS_PER_ORC = 247,
		APPLY_ATTBONUS_PER_MILGYO = 248,
		APPLY_ATTBONUS_PER_UNDEAD = 249,
		APPLY_ATTBONUS_PER_DEVIL = 250,
		APPLY_ENCHANT_PER_ELECT = 251,
		APPLY_ENCHANT_PER_FIRE = 252,
		APPLY_ENCHANT_PER_ICE = 253,
		APPLY_ENCHANT_PER_WIND = 254,
		APPLY_ENCHANT_PER_EARTH = 255,
		APPLY_ENCHANT_PER_DARK = 256,
		APPLY_ATTBONUS_PER_CZ = 257,
		APPLY_ATTBONUS_PER_INSECT = 258,
		APPLY_ATTBONUS_PER_DESERT = 259,
		APPLY_ATTBONUS_PER_STONE = 260,
		APPLY_ATTBONUS_PER_MONSTER = 261,
		APPLY_RESIST_PER_HUMAN = 262,
		APPLY_RESIST_PER_ICE = 263,
		APPLY_RESIST_PER_DARK = 264,
		APPLY_RESIST_PER_EARTH = 265,
		APPLY_RESIST_PER_FIRE = 266,
		APPLY_RESIST_PER_ELEC = 267,
		APPLY_RESIST_PER_MAGIC = 268,
		APPLY_RESIST_PER_WIND = 269,
		APPLY_HIT_BUFF_SUNGMA_STR = 270,
		APPLY_HIT_BUFF_SUNGMA_MOVE = 271,
		APPLY_HIT_BUFF_SUNGMA_HP = 272,
		APPLY_HIT_BUFF_SUNGMA_IMMUNE = 273,
		APPLY_MOUNT_MELEE_MAGIC_ATTBONUS_PER = 274,
		APPLY_DISMOUNT_MOVE_SPEED_BONUS_PER = 275,
		APPLY_HIT_AUTO_HP_RECOVERY = 276,
		APPLY_HIT_AUTO_SP_RECOVERY = 277,
		APPLY_USE_SKILL_COOLTIME_DECREASE_ALL = 278,
		APPLY_HIT_STONE_ATTBONUS_STONE = 279,
		APPLY_HIT_STONE_DEF_GRADE_BONUS = 280,
		APPLY_KILL_BOSS_ITEM_BONUS = 281,
		APPLY_MOB_HIT_MOB_AGGRESSIVE = 282,
		APPLY_NO_DEATH_AND_HP_RECOVERY30 = 283,
		APPLY_AUTO_PICKUP = 284,
		APPLY_MOUNT_NO_KNOCKBACK = 285,
		APPLY_SUNGMA_PER_STR = 286,
		APPLY_SUNGMA_PER_HP = 287,
		APPLY_SUNGMA_PER_MOVE = 288,
		APPLY_SUNGMA_PER_IMMUNE = 289,
		APPLY_IMMUNE_POISON100 = 290,
		APPLY_IMMUNE_BLEEDING100 = 291,
		APPLY_MONSTER_DEFEND_BONUS = 292,
#endif

		MAX_APPLY_NUM
	};

	enum EImmuneFlags
	{
		IMMUNE_PARA		= (1 << 0), // Blitz
		IMMUNE_CURSE	= (1 << 1), // Fluch
		IMMUNE_STUN		= (1 << 2), // Ohnmacht
		IMMUNE_SLEEP	= (1 << 3), // Schlaf
		IMMUNE_SLOW		= (1 << 4), // Verlangsermen
		IMMUNE_POISON	= (1 << 5), // Gift
		IMMUNE_TERROR	= (1 << 6), // Terror?

#ifdef ENABLE_INGAME_WIKI
		IMMUNE_FLAG_MAX_NUM = 7
#endif
	};

#ifdef ENABLE_PROTO_RENEWAL
	enum EMaskType
	{
		MASK_ITEM_TYPE_NONE,				// 0
		MASK_ITEM_TYPE_MOUNT_PET,			// Mounts | Pets
		MASK_ITEM_TYPE_EQUIPMENT_WEAPON,	// Weapons
		MASK_ITEM_TYPE_EQUIPMENT_ARMOR,		// Equipment
		MASK_ITEM_TYPE_EQUIPMENT_JEWELRY,	// Jewellery
		MASK_ITEM_TYPE_TUNING,				// Upgrades
		MASK_ITEM_TYPE_POTION,				// Potions
		MASK_ITEM_TYPE_FISHING_PICK,		// Fishing | Mining
		MASK_ITEM_TYPE_DRAGON_STONE,		// Dragon Stone Alchemy
		MASK_ITEM_TYPE_COSTUMES,			// Costumes
		MASK_ITEM_TYPE_SKILL,				// Skills
		MASK_ITEM_TYPE_UNIQUE,				// Special Items
		MASK_ITEM_TYPE_ETC,					// Others
		MASK_ITEM_TYPE_MAX					// 14
	};

	enum EMaskSubTypeMountPet
	{
		MASK_ITEM_SUBTYPE_MOUNT_PET_MOUNT,			// Mounts
		MASK_ITEM_SUBTYPE_MOUNT_PET_CHARGED_PET,	// Pets
		MASK_ITEM_SUBTYPE_MOUNT_PET_FREE_PET,		// Evolvable Pets
		MASK_ITEM_SUBTYPE_MOUNT_PET_EGG				// Pet Eggs
	};

	enum EMaskSubTypeWeapon
	{
		MASK_ITEM_SUBTYPE_WEAPON_WEAPON_SWORD,		// One-Handed Swords
		MASK_ITEM_SUBTYPE_WEAPON_WEAPON_DAGGER,		// Daggers
		MASK_ITEM_SUBTYPE_WEAPON_WEAPON_BOW,		// Bows
		MASK_ITEM_SUBTYPE_WEAPON_WEAPON_TWO_HANDED,	// Two-Handed Swords
		MASK_ITEM_SUBTYPE_WEAPON_WEAPON_BELL,		// Bells
		MASK_ITEM_SUBTYPE_WEAPON_WEAPON_CLAW,		// Claws
		MASK_ITEM_SUBTYPE_WEAPON_WEAPON_FAN,		// Fans
		MASK_ITEM_SUBTYPE_WEAPON_WEAPON_MOUNT_SPEAR,// Spears (lanzas)
		MASK_ITEM_SUBTYPE_WEAPON_WEAPON_ARROW,		// Arrows
		MASK_ITEM_SUBTYPE_WEAPON_WEAPON_QUIVER,		// Quivers
	};

	enum EMaskSubTypeArmor
	{
		MASK_ITEM_SUBTYPE_ARMOR_ARMOR_BODY,		// Armour
		MASK_ITEM_SUBTYPE_ARMOR_ARMOR_HEAD,		// Helmets
		MASK_ITEM_SUBTYPE_ARMOR_ARMOR_SHIELD,	// Shields
#	ifdef ENABLE_GLOVE_SYSTEM
		MASK_ITEM_SUBTYPE_ARMOR_ARMOR_GLOVE		//Handschuhe
#	endif
	};

	enum EMaskSubTypeJewelry
	{
		MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_WRIST,	// Bracelets
		MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_FOOTS,	// Shoes
		MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_NECK,	// Necklaces
		MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_EAR,	// Earrrings
		MASK_ITEM_SUBTYPE_JEWELRY_ITEM_BELT,	// Belts
		MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_PENDANT,	// Talisman
	};

	enum EMaskSubTypeTuning
	{
		MASK_ITEM_SUBTYPE_TUNING_RESOURCE,	// Materials
		MASK_ITEM_SUBTYPE_TUNING_STONE,		// Spirit Stones
		MASK_ITEM_SUBTYPE_TUNING_ETC		// Other
	};

	enum EMaskSubTypePotion
	{
		MASK_ITEM_SUBTYPE_POTION_ABILITY,	// Consumables
		MASK_ITEM_SUBTYPE_POTION_HAIRDYE,	// Hair Dyes (tintes de pelo)
		MASK_ITEM_SUBTYPE_POTION_ETC		// Other
	};

	enum EMaskSubTypeFishingPick
	{
		MASK_ITEM_SUBTYPE_FISHING_PICK_FISHING_POLE,	// Fishing Rods
		MASK_ITEM_SUBTYPE_FISHING_PICK_EQUIPMENT_PICK,	// Pickaxes
		MASK_ITEM_SUBTYPE_FISHING_PICK_FOOD,			// Fish
		MASK_ITEM_SUBTYPE_FISHING_PICK_STONE,			// Ores (Minerales)
		MASK_ITEM_SUBTYPE_FISHING_PICK_ETC				// Other
	};

	enum EMaskSubTypeDragonStone
	{
		MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_DIAMOND,	// Diamond
		MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_RUBY,		// Ruby
		MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_JADE,		// Jade
		MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_SAPPHIRE,	// Sapphire
		MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_GARNET,	// Garnet
		MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_ONYX,		// Onyx
		MASK_ITEM_SUBTYPE_DRAGON_STONE_ETC				// Other
	};

	enum EMaskSubTypeCostumes
	{
		MASK_ITEM_SUBTYPE_COSTUMES_COSTUME_WEAPON,	// Weapon Skins
		MASK_ITEM_SUBTYPE_COSTUMES_COSTUME_BODY,	// Costumes
		MASK_ITEM_SUBTYPE_COSTUMES_COSTUME_HAIR,	// Hairstyles
		MASK_ITEM_SUBTYPE_COSTUMES_SASH,			// Shoulder Sashes
		MASK_ITEM_SUBTYPE_COSTUMES_ETC,				// Other
#ifdef ENABLE_AURA_SYSTEM
		MASK_ITEM_SUBTYPE_COSTUMES_AURA,
#endif
	};

	enum EMaskSubTypeSkill
	{
		MASK_ITEM_SUBTYPE_SKILL_PAHAE,				// Ward | Boost (Contraataque | Potenciacion)
		MASK_ITEM_SUBTYPE_SKILL_SKILL_BOOK,			// Skills Books
		MASK_ITEM_SUBTYPE_SKILL_BOOK_OF_OBLIVION,	// Books of Forgetfulness
		MASK_ITEM_SUBTYPE_SKILL_ETC,				// Other
		MASK_ITEM_SUBTYPE_SKILL_SKILL_BOOK_HORSE
	};

	enum EMaskSubTypeUnique
	{
		MASK_ITEM_SUBTYPE_UNIQUE_ABILITY,			// Consumables
		MASK_ITEM_SUBTYPE_UNIQUE_ETC				// Others
	};

	enum EMaskSubTypeEtc
	{
		MASK_ITEM_SUBTYPE_ETC_GIFTBOX,		// Chests | Boxes
		MASK_ITEM_SUBTYPE_ETC_MATRIMORY,	// Marriage
		MASK_ITEM_SUBTYPE_ETC_EVENT,		// Event Items
		MASK_ITEM_SUBTYPE_ETC_SEAL,			// Soulbinding
		MASK_ITEM_SUBTYPE_ETC_PARTI,		// Art of War Books
		MASK_ITEM_SUBTYPE_ETC_POLYMORPH,	// Polymorph Marbles
		MASK_ITEM_SUBTYPE_ETC_RECIPE,		// Potion Production
		MASK_ITEM_SUBTYPE_ETC_ETC			// Other
	};
#endif

#pragma pack(push)
#pragma pack(1)
	typedef struct SItemLimit
	{
		uint8_t		bType;
		long		lValue;
	} TItemLimit;

	typedef struct SItemApply
	{
		uint16_t	wType;	//@fixme436
		long		lValue;
	} TItemApply;

	typedef struct SItemTable
	{
		uint32_t	dwVnum;
		uint32_t	dwVnumRange;							//ITEM_VNUM~RANGE
		char		szName[ITEM_NAME_MAX_LEN + 1];			//ITEM_NAME(K)
		char		szLocaleName[ITEM_NAME_MAX_LEN + 1];
		uint8_t		bType;									//ITEM_TYPE
		uint8_t		bSubType;								//SUB_TYPE

		uint8_t		bWeight;								//0
		uint8_t		bSize;									//SIZE

		uint32_t	dwAntiFlags;							//ANTI_FLAG
		uint32_t	dwFlags;								//FLAG
		uint32_t	dwWearFlags;							//ITEM_WEAR
		uint32_t	dwImmuneFlag;							//IMMUNE

		uint32_t	dwIBuyItemPrice;						//GOLD
		uint32_t	dwISellItemPrice;						//SHOP_BUY_PRICE

		TItemLimit	aLimits[ITEM_LIMIT_MAX_NUM];			//LIMIT_TYPE0,LIMIT_VALUE0, LIMIT_TYPE1,LIMIT_VALUE1
		TItemApply	aApplies[ITEM_APPLY_MAX_NUM];			//ADDON_TYPE0,ADDON_VALUE0, ADDON_TYPE1,ADDON_VALUE1, ADDON_TYPE2,ADDON_VALUE2, ADDON_TYPE3,ADDON_VALUE3
		long		alValues[ITEM_VALUES_MAX_NUM];			//VALUE0,VALUE1,VALUE2,VALUE3,VALUE4,VALUE5
		long		alSockets[ITEM_SOCKET_MAX_NUM];			//SOCKET

#ifdef ENABLE_PROTO_RENEWAL
		uint32_t	dwRefineElementApplyType;
		uint32_t	dwRefineElementGrade;
		uint32_t	dwRefineElementValue;
		uint32_t	dwRefineElementBonus;
#endif

		uint32_t	dwRefinedVnum;							//REFINE
		uint16_t	wRefineSet;								//REFINESET
#ifdef ENABLE_PROTO_RENEWAL
		uint32_t	dwMaterial67;
#endif
		uint8_t		bAlterToMagicItemPct;					//MAGIC_PCT
		uint8_t		bSpecular;								//Specular
		uint8_t		bGainSocketPct;							//ATTU_ADDON
#ifdef ENABLE_PROTO_RENEWAL
		uint8_t		bMaskType;
		uint8_t		bMaskSubType;
#endif
	//	short int	sAddonType;
	} TItemTable;

#pragma pack(pop)

public:
	CItemData();
	virtual ~CItemData();

	void Clear();
	void SetSummary(const std::string & c_rstSumm);
	void SetDescription(const std::string & c_rstDesc);

	CGraphicThing * GetModelThing();
	CGraphicThing * GetSubModelThing();
	CGraphicThing * GetDropModelThing();
	CGraphicSubImage * GetIconImage();

	uint32_t GetLODModelThingCount();
	BOOL GetLODModelThingPointer(uint32_t dwIndex, CGraphicThing ** ppModelThing);

	uint32_t GetAttachingDataCount();
	BOOL GetCollisionDataPointer(uint32_t dwIndex, const NRaceData::TAttachingData ** c_ppAttachingData);
	BOOL GetAttachingDataPointer(uint32_t dwIndex, const NRaceData::TAttachingData ** c_ppAttachingData);

	/////
	const TItemTable * GetTable() const;
	uint32_t GetIndex() const;
	uint32_t GetRefinedVnum() const;
#ifdef ENABLE_SOULBIND_SYSTEM
	BOOL CanSealItem() const;
#endif
#ifdef ENABLE_ATTR_6TH_7TH
	BOOL IsAttr67MaterialVnum() const;
#endif
	const char * GetName() const;
	const char * GetDescription() const;
	const char * GetSummary() const;
	uint8_t GetType() const;
	uint8_t GetSubType() const;
#ifdef ENABLE_MOVE_COSTUME_ATTR
	uint8_t GetMagicPct() const;
#endif
#ifdef ENABLE_PROTO_RENEWAL
	uint8_t GetMaskType() const;
	uint8_t GetMaskSubType() const;
#endif
#ifdef ENABLE_CHANGE_LOOK_SYSTEM
	uint32_t GetAntiFlags() const;
#endif
	uint32_t GetRefine() const;
	const char * GetUseTypeString() const;
	uint32_t GetWeaponType() const;
	uint8_t GetSize() const;
	BOOL IsAntiFlag(uint32_t dwFlag) const;
	BOOL IsFlag(uint32_t dwFlag) const;
	BOOL IsWearableFlag(uint32_t dwFlag) const;
	BOOL HasNextGrade() const;
	uint32_t GetWearFlags() const;
	uint32_t GetIBuyItemPrice() const;
	uint32_t GetISellItemPrice() const;
	BOOL GetLimit(uint8_t byIndex, TItemLimit * pItemLimit) const;
	BOOL GetApply(uint8_t byIndex, TItemApply * pItemApply) const;
	long GetValue(uint8_t byIndex) const;
	long GetSocket(uint8_t byIndex) const;
	long SetSocket(uint8_t byIndex, uint32_t value);
	int GetSocketCount() const;
	uint32_t GetIconNumber() const;

	uint32_t GetSpecularPoweru() const;
	float GetSpecularPowerf() const;

	/////

	BOOL IsEquipment() const;

	/////

#ifdef ENABLE_SOULBIND_SYSTEM
	bool IsSealAbleItem() const;
#endif

	//BOOL LoadItemData(const char * c_szFileName);
	void SetDefaultItemData(const char * c_szIconFileName, const char * c_szModelFileName = nullptr);
	void SetItemTableData(TItemTable * pItemTable);

#ifdef ENABLE_INGAME_WIKI
public:
	typedef struct SWikiItemInfo
	{
		~SWikiItemInfo() = default;
		SWikiItemInfo() {
			isSet = false;
			hasData = false;
			bIsCommon = false;

			dwOrigin = 0;
			maxRefineLevel = WIKI_MAX_REFINE_COUNT;

			pRefineData.clear();
			pChestInfo.clear();
			pOriginInfo.clear();
		}

		bool isSet;
		bool hasData;
		bool bIsCommon;

		uint32_t dwOrigin;
		int maxRefineLevel;

		std::vector<NWikiData::TWikiRefineInfo> pRefineData;
		std::vector<NWikiData::TWikiChestInfo> pChestInfo;
		std::vector<NWikiData::TWikiItemOriginInfo> pOriginInfo;
	} TWikiItemInfo;

	bool IsValidImage() { return m_isValidImage; }
	std::string GetIconFileName() { return m_strIconFileName; }
	TWikiItemInfo* GetWikiTable() { return &m_wikiInfo; }
	bool IsBlacklisted() { return m_isBlacklisted; }

	void ValidateImage(bool isValidImage) { m_isValidImage = isValidImage; }
	void SetBlacklisted(bool val) { m_isBlacklisted = val; }

protected:
	bool m_isValidImage;
	bool m_isBlacklisted;

private:
	TWikiItemInfo m_wikiInfo;
#endif

#ifdef ENABLE_SHINING_SYSTEM
public:
	enum ELoadShining
	{
		ITEM_SHINING_MAX_COUNT = 3,
		ITEM_SHINING_MAX_ROW = 256,
	};

	typedef struct SItemShiningTable
	{
		char szShinings[ITEM_SHINING_MAX_COUNT][ITEM_SHINING_MAX_ROW];
		bool Any() const; //Checking if any shining is set for this item.
	} TItemShiningTable;

	void SetItemShiningTableData(uint8_t bIndex, const char* szEffectname) { sprintf(m_ItemShiningTable.szShinings[bIndex], szEffectname); }
	CItemData::TItemShiningTable GetItemShiningTable() { return m_ItemShiningTable; }
#endif

protected:
	void __LoadFiles();
	void __SetIconImage(const char * c_szFileName);

protected:
	std::string m_strModelFileName;
	std::string m_strSubModelFileName;
	std::string m_strDropModelFileName;
	std::string m_strIconFileName;
	std::string m_strDescription;
	std::string m_strSummary;
	std::vector<std::string> m_strLODModelFileNameVector;

	CGraphicThing * m_pModelThing;
	CGraphicThing * m_pSubModelThing;
	CGraphicThing * m_pDropModelThing;
	CGraphicSubImage * m_pIconImage;
	std::vector<CGraphicThing *> m_pLODModelThingVector;

	NRaceData::TAttachingDataVector m_AttachingDataVector;
	uint32_t m_dwVnum;
	TItemTable m_ItemTable;
#ifdef ENABLE_SHINING_SYSTEM
	TItemShiningTable m_ItemShiningTable;
#endif

public:
	static void DestroySystem();

	static CItemData * New();
	static void Delete(CItemData * pkItemData);

	static CDynamicPool<CItemData> ms_kPool;

#ifdef ENABLE_AURA_SYSTEM
protected:
	uint32_t m_dwAuraEffectID;
public:
	void SetAuraEffectID(const char* szAuraEffectPath);
	uint32_t GetAuraEffectID() const { return m_dwAuraEffectID; }
#endif

#ifdef ENABLE_SCALE_SYSTEM
protected:
	typedef struct SItemScaleTable
	{
		D3DXVECTOR3 v3MeshScale[NRaceData::SEX_MAX_NUM][NRaceData::JOB_MAX_NUM];
		float fParticleScale[NRaceData::SEX_MAX_NUM][NRaceData::JOB_MAX_NUM];
	} TItemScaleTable;
	TItemScaleTable m_ItemScaleTable;

public:
	float GetItemParticleScale(uint8_t byJob, uint8_t bySex);
	void SetItemTableScaleData(uint8_t byJob, uint8_t bySex, float fMeshScaleX, float fMeshScaleY, float fMeshScaleZ, float fParticleScale);
	D3DXVECTOR3& GetItemScaleVector(uint8_t byJob, uint8_t bySex);
#endif
};

inline bool operator<(const CItemData::TItemTable & lhs, const CItemData::TItemTable & rhs)
{
	return lhs.dwVnum < rhs.dwVnum;
}
